#pragma config(Motor,  motor1,          rampMotor, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor2,          leftLiftMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          intake,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor8,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
//#pragma config(Motor,  motor9,          basketMotor,   tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



/*------------------------------------------------------------------------------------------------
  This program will use the VEX IQ Wirless Controller to drive your Clawbot. This program uses
  If/Else statements to provide a "threshold" for the transmitter - this allows your robot to
  come to a stop even if the joysticks on the Wireless Controller haven't perfectly returned to
  their zero position.

  Note: You will have to set ROBOTC to enable "Wireless Control" to use the VEX IQ joystick.

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    Port 1        			leftMotor           VEX IQ Motor		      			Left side motor
    Port 6       				rightMotor          VEX IQ Motor		      			Right side motor (reversed)
		Port 10							armMotor						VEX IQ Motor								Arm Up/Down motor
		Port 11							clawMotor						VEX IQ Motor								Claw Open/Close motor
------------------------------------------------------------------------------------------------*/

task main()
{
	int threshold = 10;

	while(true)
	{
		//If the ChannelA (left Y-Axis) is greater or less than the threshold value,
		//then we'll set the speed of the arm motors to vlaue from the joystick.
		if (getJoystickValue(ChD) > threshold)
		{
					setMotorSpeed(rightMotor, getJoystickValue(ChD));
		}
		else if (getJoystickValue(ChD) < -threshold)
		{
					setMotorSpeed(rightMotor, getJoystickValue(ChD));
		}
		else  //If less than the threshold, we'll set the motor to zero.
		{
					setMotorSpeed(rightMotor, 0);
		}

  	if (getJoystickValue(ChA) > threshold)
		{
					setMotorSpeed(leftMotor, getJoystickValue(ChA));
		}
		else if (getJoystickValue(ChA) < -threshold)
		{
					setMotorSpeed(leftMotor, getJoystickValue(ChA));
		}
		else  //If less than the threshold, we'll set the motor to zero.
		{
					setMotorSpeed(leftMotor, 0);
		}

		//If Button "L-Up" or "L-Down"is pressed, we'll close the claw
		if (getJoystickValue(BtnFUp) == 1)
		{
			setMotorTarget(rampMotor, -90, 100);
			resetMotorEncoder(rampMotor);
		}
		else if (getJoystickValue(BtnFDown) == 1)
		{
			setMotorTarget(rampMotor, 90, 30);
			resetMotorEncoder(rampMotor);
		}
		else	//If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(rampMotor, 0);
		}


		//If Button "L-Up" or "L-Down"is pressed, we'll close the claw
		if (getJoystickValue(BtnLUp) == 1)
		{
			setMotorSpeed(intake, 127);
		} else if (getJoystickValue(BtnLDown) == 1) {
			setMotorSpeed(intake, -127);
		}
		else	//If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(intake, 0);
		}

		//If Button "R-Up" or "R-Down" is pressed, we'll open the claw
		if (getJoystickValue(BtnRUp) == 1) {
			setMotorSpeed(leftLiftMotor, -50);
	//		setMotorSpeed(rightLiftMotor, -50);
		} else if (getJoystickValue(BtnRDown) == 1) {
			setMotorSpeed(leftLiftMotor, 50);
	//		setMotorSpeed(rightLiftMotor, 50);
		}
		else	//If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(leftLiftMotor, 0);
		//	setMotorSpeed(rightLiftMotor, 0);
		}

		} // end of while (true)

} // end of task main ()
