#pragma config(Motor,  motor1,          rightLiftMotor, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor2,          leftLiftMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          intake,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor8,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
//#pragma config(Motor,  motor9,          basketMotor,   tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will use the VEX IQ Wirless Controller to drive your Clawbot. This program uses
  If/Else statements to provide a "threshold" for the transmitter - this allows your robot to
  come to a stop even if the joysticks on the Wireless Controller haven't perfectly returned to
  their zero position.

  Note: You will have to set ROBOTC to enable "Wireless Control" to use the VEX IQ joystick.

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    Port 1        			leftMotor           VEX IQ Motor		      			Left side motor
    Port 6       				rightMotor          VEX IQ Motor		      			Right side motor (reversed)
		Port 10							armMotor						VEX IQ Motor								Arm Up/Down motor
		Port 11							clawMotor						VEX IQ Motor								Claw Open/Close motor
------------------------------------------------------------------------------------------------*/

task main()
{
	int threshold = 10;

	while(true)
	{
		//If the ChannelA (left Y-Axis) is greater or less than the threshold value,
		//then we'll set the speed of the arm motors to vlaue from the joystick.
	if (getJoystickValue(ChC) < threshold && getJoystickValue(ChC) > -threshold)
	{
		if (getJoystickValue(ChD) > threshold)
		{
					setMotorSpeed(rightMotor, 100);
					setMotorSpeed(leftMotor, 100);
		}
		else if (getJoystickValue(ChD) < -threshold)
		{
					setMotorSpeed(rightMotor, -100);
					setMotorSpeed(leftMotor, -100);
		}
		else  //If less than the threshold, we'll set the motor to zero.
		{
					setMotorSpeed(rightMotor, 0);
					setMotorSpeed(leftMotor, 0);
		}
	}
  else
  {
	if (getJoystickValue(ChD) < threshold && getJoystickValue(ChD) > -threshold) {
  	if (getJoystickValue(ChC) > threshold)
		{
					setMotorSpeed(rightMotor, -100);
					setMotorSpeed(leftMotor, 100);
		}
		else if (getJoystickValue(ChC) < -threshold)
		{
					setMotorSpeed(rightMotor, 100);
					setMotorSpeed(leftMotor, -100);
		}
		else  //If less than the threshold, we'll set the motor to zero.
		{
					setMotorSpeed(rightMotor, 0);
					setMotorSpeed(leftMotor, 0);
		}
	}
  }

/*
		if (getJoystickValue(ChC) > threshold)
		{
//				setMotorSpeed(intake, getJoystickValue(ChA));
//				setMotorSpeed(leftMotor, getJoystickValue(ChA));
				setMotorSpeed(leftMotor, 100);
				setMotorSpeed(rightMotor, -100);
//				setMotorSpeed(rightLiftMotor, getJoystickValue(ChA));
		}
		else if(getJoystickValue(ChC) < -threshold)
		{
				setMotorSpeed(leftMotor, -100);
				setMotorSpeed(rightMotor, 100);
		}
		else  //If less than the threshold, we'll set the motor to zero.
		{
//				setMotorSpeed(intake, 0);
				setMotorSpeed(leftMotor, 0);
				setMotorSpeed(rightMotor, 0);
	//			setMotorSpeed(rightLiftMotor, 0);
		}
*/

		//If the ChannelC (right Y-Axis) is greater or less than the threshold value,
		//then we'll set the speed of the drive train motors to vlaue from the joystick.
/*
		if (getJoystickValue(ChA) > threshold)
		{
			setMotorSpeed(rightMotor, 0);
			setMotorSpeed(leftMotor, 50);
//			setMotorSpeed(rightMotor, -getJoystickValue(ChC));
//			setMotorSpeed(leftMotor, getJoystickValue(ChC));
		}
		else if (getJoystickValue(ChA) < -threshold)
		{
			setMotorSpeed(rightMotor, 50);
			setMotorSpeed(leftMotor, 0);
		}
		else  //If less than the threshold, we'll set the motor to zero.
    {
    	setMotorSpeed(rightMotor, 0);
			setMotorSpeed(leftMotor, 0);
		}
*/

		//If Button "L-Up" or "L-Down"is pressed, we'll close the claw

		if (getJoystickValue(BtnLUp) == 1)
		{
			setMotorSpeed(intake, 127);
		} else if (getJoystickValue(BtnLDown) == 1) {
			setMotorSpeed(intake, -127);
		}
		else	//If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(intake, 0);
		}

		//If Button "R-Up" or "R-Down" is pressed, we'll open the claw
		if (getJoystickValue(BtnRUp) == 1) {
			setMotorSpeed(leftLiftMotor, 10);
			setMotorSpeed(rightLiftMotor, 10);
		} else if (getJoystickValue(BtnRDown) == 1) {
			setMotorSpeed(leftLiftMotor, -10);
			setMotorSpeed(rightLiftMotor, -10);
		}
		else	//If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(leftLiftMotor, 0);
			setMotorSpeed(rightLiftMotor, 0);
		}

		} // end of while (true)

} // end of task main ()
