#pragma config(Motor,  motor12,          rampMotor, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,          leftLiftMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
//#pragma config(Motor,  motor9,          basketMotor,   tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will use the VEX IQ Wirless Controller to drive your Clawbot. This program uses
  If/Else statements to provide a "threshold" for the transmitter - this allows your robot to
  come to a stop even if the joysticks on the Wireless Controller haven't perfectly returned to
  their zero position.

  Note: You will have to set ROBOTC to enable "Wireless Control" to use the VEX IQ joystick.

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    Port 1        			leftMotor           VEX IQ Motor		      			Left side motor
    Port 6       				rightMotor          VEX IQ Motor		      			Right side motor (reversed)
		Port 10							armMotor						VEX IQ Motor								Arm Up/Down motor
		Port 11							clawMotor						VEX IQ Motor								Claw Open/Close motor
------------------------------------------------------------------------------------------------*/
//#pragma config(Motor,  motor6,          intake,        tmotorVexIQ, PIDControl, encoder)



task main()
{
	int threshold = 10;
	int direction = 1;
	int intakeOn = 0;

	while(true)
	{
		//Use Button E to control front/back diretion of robot
		if (getJoystickValue(BtnEUp) == 1)
		{
			direction = 1;
		} else if (getJoystickValue(BtnEDown) == 1) {
			direction = -1;
		}

		//Use Button F to turn intake On or Off
		if (getJoystickValue(BtnFUp) == 1)
		{
			intakeOn = 1;
		} else if (getJoystickValue(BtnFDown) == 1) {
			intakeOn = 0;
		}

		//auto-on start - middle Green cube
		//Rohan and Neel to work here
		if (getJoystickValue(BtnFDown) == 1)
		{
			resetMotorEncoder(leftMotor);
			resetMotorEncoder(rightMotor);
			setMotorTarget(leftMotor, 340, 100);
			waitUntilMotorStop(leftMotor);
			resetMotorEncoder(leftMotor);

			setMotorTarget(leftMotor, 590, 50);
			setMotorTarget(rightMotor, 590, 50);
			waitUntilMotorStop(leftMotor);
			waitUntilMotorStop(rightMotor);
			setMotorTarget(leftLiftMotor, -450, 127);
			waitUntilMotorStop(leftLiftMotor);
			resetMotorEncoder(leftMotor);
			resetMotorEncoder(rightMotor);
			resetMotorEncoder(leftLiftMotor);

			setMotorTarget(leftMotor, -20, 40);
			resetMotorEncoder(leftMotor);
			waitUntilMotorStop(leftMotor);

			setMotorTarget(leftMotor, 900, 70);
			setMotorTarget(rightMotor, 900, 70);
			waitUntilMotorStop(leftMotor);
			waitUntilMotorStop(rightMotor);
			resetMotorEncoder(leftMotor);
			resetMotorEncoder(rightMotor);

			setMotorTarget(leftLiftMotor, 225, 127);
			waitUntilMotorStop(leftLiftMotor);
			resetMotorEncoder(leftMotor);
			resetMotorEncoder(rightMotor);
			resetMotorEncoder(leftLiftMotor);
		}

		//auto-on start - first green cube
/*		if (getJoystickValue(BtnFUp) == 1)
		{
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);
				setMotorTarget(leftMotor, 95, 50);
				setMotorTarget(rightMotor, 95, 50);
				waitUntilMotorStop(leftMotor);
				waitUntilMotorStop(rightMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);

				setMotorTarget(leftMotor, 90, 100);
				waitUntilMotorStop(leftMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);

				setMotorTarget(leftMotor, -20, 100);
				setMotorTarget(rightMotor, -20, 100);
				waitUntilMotorStop(leftMotor);
				waitUntilMotorStop(rightMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);

				setMotorTarget(leftMotor, -60, 100);
				waitUntilMotorStop(leftMotor);
				resetMotorEncoder(leftMotor);

				setMotorTarget(leftMotor, 70, 50);
				setMotorTarget(rightMotor, 70, 50);
				waitUntilMotorStop(leftMotor);
				waitUntilMotorStop(rightMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);

				setMotorTarget(leftMotor, 30, 100);
				setMotorTarget(rightMotor, 30, 100);
				setMotorTarget(leftLiftMotor, -490, 100);
				waitUntilMotorStop(leftMotor);
				waitUntilMotorStop(rightMotor);
				waitUntilMotorStop(leftLiftMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);
				resetMotorEncoder(leftLiftMotor);

				setMotorTarget(rightMotor, 30, 100);
				waitUntilMotorStop(rightMotor);
				resetMotorEncoder(rightMotor);

				setMotorTarget(leftMotor, 620, 100);
				setMotorTarget(rightMotor, 620, 100);
				waitUntilMotorStop(leftMotor);
				waitUntilMotorStop(rightMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);

				setMotorTarget(leftLiftMotor, 225, 100);
				waitUntilMotorStop(leftLiftMotor);
				resetMotorEncoder(leftLiftMotor);

				setMotorTarget(leftMotor, -820, 100);
				setMotorTarget(rightMotor, -820, 100);
				waitUntilMotorStop(leftMotor);
				waitUntilMotorStop(rightMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);

				setMotorTarget(leftLiftMotor, 265, 100);
				waitUntilMotorStop(leftLiftMotor);
				resetMotorEncoder(leftLiftMotor);

		}
*/
		//auto-on end - first green cube


		if (getJoystickValue(BtnFUp) == 1){
					resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);
				setMotorTarget(leftMotor, -95, 50);
				setMotorTarget(rightMotor, -95, 50);
				waitUntilMotorStop(leftMotor);
				waitUntilMotorStop(rightMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);

				setMotorTarget(leftMotor, -100, 100);
				waitUntilMotorStop(leftMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);

				setMotorTarget(leftMotor, 20, 100);
				setMotorTarget(rightMotor, 20, 100);
				waitUntilMotorStop(leftMotor);
				waitUntilMotorStop(rightMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);

				setMotorTarget(leftMotor, 60, 100);
				waitUntilMotorStop(leftMotor);
				resetMotorEncoder(leftMotor);

				setMotorTarget(leftMotor, -150, 30);
				setMotorTarget(rightMotor, -150, 30);
				waitUntilMotorStop(leftMotor);
				waitUntilMotorStop(rightMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);

				setMotorTarget(rampMotor, -475, 100);
				waitUntilMotorStop(rampMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);
				resetMotorEncoder(rampMotor);

				setMotorTarget(leftMotor, -275, 100);
				setMotorTarget(rightMotor, 275, 100);
				waitUntilMotorStop(leftMotor);
				waitUntilMotorStop(rightMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);

				setMotorTarget(leftMotor, -600, 100);
				setMotorTarget(rightMotor, -600, 100);
				waitUntilMotorStop(leftMotor);
				waitUntilMotorStop(rightMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);

				setMotorTarget(rampMotor, 275, 100);
				waitUntilMotorStop(rampMotor);
				resetMotorEncoder(rampMotor);
				wait(1000);

				setMotorTarget(leftMotor, 600, 100);
				setMotorTarget(rightMotor, 600, 100);
				waitUntilMotorStop(leftMotor);
				waitUntilMotorStop(rightMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);
		}

		if (direction == 1) { // forward direction
	// in forward diretion, ChannelD controls right motor of robot
		if (getJoystickValue(ChD) > threshold)
		{
			// setMotorSpeed(rightMotor, 100);
					setMotorSpeed(rightMotor, getJoystickValue(ChD));
		}
		else if (getJoystickValue(ChD) < -threshold)
		{
			// setMotorSpeed(rightMotor, -100);
					setMotorSpeed(rightMotor, getJoystickValue(ChD));
		}
		else  //If less than the threshold, we'll set the motor to zero.
		{
					setMotorSpeed(rightMotor, 0);
		}

	// in forward diretion, ChannelA controls left motor of robot
  	if (getJoystickValue(ChA) > threshold)
		{
			// setMotorSpeed(leftMotor, 100);
					setMotorSpeed(leftMotor, getJoystickValue(ChA));
		}
		else if (getJoystickValue(ChA) < -threshold)
		{
			// setMotorSpeed(leftMotor, -100);
					setMotorSpeed(leftMotor, getJoystickValue(ChA));
		}
		else  //If less than the threshold, we'll set the motor to zero.
		{
					setMotorSpeed(leftMotor, 0);
		}
	}
	else // reverse direction
	{
	// in reverse diretion, ChannelD controls left motor of robot
		if (getJoystickValue(ChD) > threshold)
		{
					setMotorSpeed(leftMotor, direction * getJoystickValue(ChD));
		}
		else if (getJoystickValue(ChD) < -threshold)
		{
					setMotorSpeed(leftMotor, direction * getJoystickValue(ChD));
		}
		else  //If less than the threshold, we'll set the motor to zero.
		{
					setMotorSpeed(leftMotor, 0);
		}

	// in reverse diretion, ChannelA controls right motor of robot
  	if (getJoystickValue(ChA) > threshold)
		{
					setMotorSpeed(rightMotor, direction * getJoystickValue(ChA));
		}
		else if (getJoystickValue(ChA) < -threshold)
		{
					setMotorSpeed(rightMotor, direction * getJoystickValue(ChA));
		}
		else  //If less than the threshold, we'll set the motor to zero.
		{
					setMotorSpeed(rightMotor, 0);
		}
	}

// Button "F-Up" or "F-Down"is pressed, operate the intake
	/* here
		if (intakeOn == 1) // reverse intake
		{
			if (direction == 1)
			{
				setMotorSpeed(intake, 127);
			}
			else
			{
				setMotorSpeed(intake, -127);
			}
		}
		else if (intakeOn == 0)  // forward intake
		{
			setMotorSpeed(intake, 0);
		}
*/ // here

		//If Button "L-Up" or "L-Down"is pressed, operate the ramp
		if (getJoystickValue(BtnRUp) == 1)
		{
			/*
			if (direction == -1) {
				setMotorTarget(rampMotor, -90, 100);
				resetMotorEncoder(rampMotor);
			} else {
			*/
				setMotorSpeed(leftLiftMotor, -100);
			// }
		}
		else if (getJoystickValue(BtnRDown) == 1)
		{
			/*
			if (direction == -1) {
				setMotorTarget(rampMotor, 90, 50);
				resetMotorEncoder(rampMotor);
			} else {
			*/
				setMotorSpeed(leftLiftMotor, 100);
			// }
		}
		else	//If neither button is pressed, we'll set the motor off.
		{
			/*
			if (direction == -1) {
				// do nothing to ramp motor
			} else {
			*/
				setMotorSpeed(leftLiftMotor, 0);
			// }
		}

		//If Button "R-Up" or "R-Down" is pressed, we'll open the claw
		if (getJoystickValue(BtnLUp) == 1) {
			// if (direction == 1) {
				setMotorTarget(rampMotor, -30, 100);
				resetMotorEncoder(rampMotor);
			// } else {
			// setMotorSpeed(leftLiftMotor, -50);
			// }
		} else if (getJoystickValue(BtnLDown) == 1) {
			// if (direction == 1) {
				setMotorTarget(rampMotor, 30, 100);
				resetMotorEncoder(rampMotor);
			// } else {
			//	setMotorSpeed(leftLiftMotor, 50);
			// }
		}
		else	//If neither button is pressed, we'll set the motor off.
		{
			// if (direction == 1) {
				// do nothing to ramp motor
			// } else {
			// 	setMotorSpeed(leftLiftMotor, 0);
			// }
		}

		} // end of while (true)

} // end of task main ()222222
