#pragma config(Motor,  motor12,          rampMotor, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,          leftLiftMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          intake,     tmotorVexIQ, PIDControl, encoder)

//#pragma config(Motor,  motor9,          basketMotor,   tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will use the VEX IQ Wirless Controller to drive your Clawbot. This program uses
  If/Else statements to provide a "threshold" for the transmitter - this allows your robot to
  come to a stop even if the joysticks on the Wireless Controller haven't perfectly returned to
  their zero position.

  Note: You will have to set ROBOTC to enable "Wireless Control" to use the VEX IQ joystick.

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    Port 1        			leftMotor           VEX IQ Motor		      			Left side motor
    Port 6       				rightMotor          VEX IQ Motor		      			Right side motor (reversed)
		Port 10							armMotor						VEX IQ Motor								Arm Up/Down motor
		Port 11							clawMotor						VEX IQ Motor								Claw Open/Close motor
------------------------------------------------------------------------------------------------*/
//#pragma config(Motor,  motor6,          intake,        tmotorVexIQ, PIDControl, encoder)



task main()
{
		//auto-on start - middle Green cube
//		if (getJoystickValue(BtnFDown) == 1)
//		{
			resetMotorEncoder(leftMotor);
			resetMotorEncoder(rightMotor);
			setMotorTarget(leftMotor, 320, 100);
			waitUntilMotorStop(leftMotor);
			resetMotorEncoder(leftMotor);

			setMotorTarget(leftMotor, 590, 50);
			setMotorTarget(rightMotor, 590, 50);
			waitUntilMotorStop(leftMotor);
			waitUntilMotorStop(rightMotor);
			setMotorTarget(leftLiftMotor, -460, 100);
			waitUntilMotorStop(leftLiftMotor);
			resetMotorEncoder(leftMotor);
			resetMotorEncoder(rightMotor);
			resetMotorEncoder(leftLiftMotor);

			setMotorTarget(leftMotor, -70, 40);
			resetMotorEncoder(leftMotor);
			waitUntilMotorStop(leftMotor);

			setMotorTarget(leftMotor, 780, 70);
			setMotorTarget(rightMotor, 780, 70);
			waitUntilMotorStop(leftMotor);
			waitUntilMotorStop(rightMotor);
			resetMotorEncoder(leftMotor);
			resetMotorEncoder(rightMotor);

			setMotorTarget(leftLiftMotor, 300, 100);
			waitUntilMotorStop(leftLiftMotor);
			resetMotorEncoder(leftMotor);
			resetMotorEncoder(rightMotor);
			resetMotorEncoder(leftLiftMotor);
//		}
} // end of task main ()222222
