#pragma config(Motor,  motor12,          rampMotor, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,          leftLiftMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          intake,     tmotorVexIQ, PIDControl, encoder)

//#pragma config(Motor,  motor9,          basketMotor,   tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will use the VEX IQ Wirless Controller to drive your Clawbot. This program uses
  If/Else statements to provide a "threshold" for the transmitter - this allows your robot to
  come to a stop even if the joysticks on the Wireless Controller haven't perfectly returned to
  their zero position.

  Note: You will have to set ROBOTC to enable "Wireless Control" to use the VEX IQ joystick.

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    Port 1        			leftMotor           VEX IQ Motor		      			Left side motor
    Port 6       				rightMotor          VEX IQ Motor		      			Right side motor (reversed)
		Port 10							armMotor						VEX IQ Motor								Arm Up/Down motor
		Port 11							clawMotor						VEX IQ Motor								Claw Open/Close motor
------------------------------------------------------------------------------------------------*/
//#pragma config(Motor,  motor6,          intake,        tmotorVexIQ, PIDControl, encoder)



task main()
{
//		if (getJoystickValue(BtnFUp) == 1)
// 			{
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);
				setMotorTarget(leftMotor, -95, 50);
				setMotorTarget(rightMotor, -95, 50);
				waitUntilMotorStop(leftMotor);
				waitUntilMotorStop(rightMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);

				setMotorTarget(leftMotor, -100, 100);
				waitUntilMotorStop(leftMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);

				setMotorTarget(leftMotor, 20, 100);
				setMotorTarget(rightMotor, 20, 100);
				waitUntilMotorStop(leftMotor);
				waitUntilMotorStop(rightMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);

				setMotorTarget(leftMotor, 60, 100);
				waitUntilMotorStop(leftMotor);
				resetMotorEncoder(leftMotor);

				setMotorTarget(leftMotor, -150, 30);
				setMotorTarget(rightMotor, -150, 30);
				waitUntilMotorStop(leftMotor);
				waitUntilMotorStop(rightMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);

				setMotorTarget(rampMotor, -475, 100);
				waitUntilMotorStop(rampMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);
				resetMotorEncoder(rampMotor);

				setMotorTarget(leftMotor, -275, 100);
				setMotorTarget(rightMotor, 275, 100);
				waitUntilMotorStop(leftMotor);
				waitUntilMotorStop(rightMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);

				setMotorTarget(leftMotor, -600, 100);
				setMotorTarget(rightMotor, -600, 100);
				waitUntilMotorStop(leftMotor);
				waitUntilMotorStop(rightMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);

				setMotorTarget(rampMotor, 275, 100);
				waitUntilMotorStop(rampMotor);
				resetMotorEncoder(rampMotor);
				wait(1000);

				setMotorTarget(leftMotor, 600, 100);
				setMotorTarget(rightMotor, 600, 100);
				waitUntilMotorStop(leftMotor);
				waitUntilMotorStop(rightMotor);
				resetMotorEncoder(leftMotor);
				resetMotorEncoder(rightMotor);
//		}
} // end of task main ()222222
