#pragma config(Motor,  motor12,          rampMotor, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor11,          leftLiftMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          intake,     tmotorVexIQ, PIDControl, encoder)

//#pragma config(Motor,  motor9,          basketMotor,   tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will use the VEX IQ Wirless Controller to drive your Clawbot. This program uses
  If/Else statements to provide a "threshold" for the transmitter - this allows your robot to
  come to a stop even if the joysticks on the Wireless Controller haven't perfectly returned to
  their zero position.

  Note: You will have to set ROBOTC to enable "Wireless Control" to use the VEX IQ joystick.

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    Port 1        			leftMotor           VEX IQ Motor		      			Left side motor
    Port 6       				rightMotor          VEX IQ Motor		      			Right side motor (reversed)
		Port 10							armMotor						VEX IQ Motor								Arm Up/Down motor
		Port 11							clawMotor						VEX IQ Motor								Claw Open/Close motor
------------------------------------------------------------------------------------------------*/
//#pragma config(Motor,  motor6,          intake,        tmotorVexIQ, PIDControl, encoder)



task main()
{
	int threshold = 10;
	int direction = 1;
	int intakeOn = 0;

	while(true)
	{
		//Use Button E to control front/back diretion of robot
		if (getJoystickValue(BtnEUp) == 1)
		{
			direction = 1;
		} else if (getJoystickValue(BtnEDown) == 1) {
			direction = -1;
		}

		//Use Button F to turn intake On or Off
		if (getJoystickValue(BtnFUp) == 1)
		{
			intakeOn = 1;
		} else if (getJoystickValue(BtnFDown) == 1) {
			intakeOn = 0;
		}

		if (direction == 1) { // forward direction
	// in forward diretion, ChannelD controls right motor of robot
		if (getJoystickValue(ChD) > threshold)
		{
			// setMotorSpeed(rightMotor, 100);
					setMotorSpeed(rightMotor, getJoystickValue(ChD));
		}
		else if (getJoystickValue(ChD) < -threshold)
		{
			// setMotorSpeed(rightMotor, -100);
					setMotorSpeed(rightMotor, getJoystickValue(ChD));
		}
		else  //If less than the threshold, we'll set the motor to zero.
		{
					setMotorSpeed(rightMotor, 0);
		}

	// in forward diretion, ChannelA controls left motor of robot
  	if (getJoystickValue(ChA) > threshold)
		{
			// setMotorSpeed(leftMotor, 100);
					setMotorSpeed(leftMotor, getJoystickValue(ChA));
		}
		else if (getJoystickValue(ChA) < -threshold)
		{
			// setMotorSpeed(leftMotor, -100);
					setMotorSpeed(leftMotor, getJoystickValue(ChA));
		}
		else  //If less than the threshold, we'll set the motor to zero.
		{
					setMotorSpeed(leftMotor, 0);
		}
	}
	else // reverse direction
	{
	// in reverse diretion, ChannelD controls left motor of robot
		if (getJoystickValue(ChD) > threshold)
		{
					setMotorSpeed(leftMotor, direction * getJoystickValue(ChD));
		}
		else if (getJoystickValue(ChD) < -threshold)
		{
					setMotorSpeed(leftMotor, direction * getJoystickValue(ChD));
		}
		else  //If less than the threshold, we'll set the motor to zero.
		{
					setMotorSpeed(leftMotor, 0);
		}

	// in reverse diretion, ChannelA controls right motor of robot
  	if (getJoystickValue(ChA) > threshold)
		{
					setMotorSpeed(rightMotor, direction * getJoystickValue(ChA));
		}
		else if (getJoystickValue(ChA) < -threshold)
		{
					setMotorSpeed(rightMotor, direction * getJoystickValue(ChA));
		}
		else  //If less than the threshold, we'll set the motor to zero.
		{
					setMotorSpeed(rightMotor, 0);
		}
	}

// Button "F-Up" or "F-Down"is pressed, operate the intake
		if (intakeOn == 1) // start intake
		{
			if (direction == 1)
			{
				setMotorSpeed(intake, -127);
			}
			else
			{
				setMotorSpeed(intake, 127);
			}
		}
		else if (intakeOn == 0)  // stop intake
		{
			setMotorSpeed(intake, 0);
		}

		//If Button "L-Up" or "L-Down"is pressed, operate the ramp
		if (getJoystickValue(BtnRUp) == 1)
		{
			/*
			if (direction == -1) {
				setMotorTarget(rampMotor, -90, 100);
				resetMotorEncoder(rampMotor);
			} else {
			*/
				setMotorSpeed(leftLiftMotor, -127);
			// }
		}
		else if (getJoystickValue(BtnRDown) == 1)
		{
			/*
			if (direction == -1) {
				setMotorTarget(rampMotor, 90, 50);
				resetMotorEncoder(rampMotor);
			} else {
			*/
				setMotorSpeed(leftLiftMotor, 50);
			// }
		}
		else	//If neither button is pressed, we'll set the motor off.
		{
			/*
			if (direction == -1) {
				// do nothing to ramp motor
			} else {
			*/
				setMotorSpeed(leftLiftMotor, 0);
			// }
		}

		//If Button "R-Up" or "R-Down" is pressed, we'll open the claw
		if (getJoystickValue(BtnLUp) == 1) {
			// if (direction == 1) {
				setMotorTarget(rampMotor, -30, 127);
				resetMotorEncoder(rampMotor);
			// } else {
			// setMotorSpeed(leftLiftMotor, -50);
			// }
		} else if (getJoystickValue(BtnLDown) == 1) {
			// if (direction == 1) {
				setMotorTarget(rampMotor, 30, 127);
				resetMotorEncoder(rampMotor);
			// } else {
			//	setMotorSpeed(leftLiftMotor, 50);
			// }
		}
		else	//If neither button is pressed, we'll set the motor off.
		{
			// if (direction == 1) {
				// do nothing to ramp motor
			// } else {
			// 	setMotorSpeed(leftLiftMotor, 0);
			// }
		}

		} // end of while (true)

} // end of task main ()222222
