#pragma config(Motor,  motor1,          rampMotor, tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor2,          leftLiftMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          intake,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor8,          leftMotor,     tmotorVexIQ, PIDControl, encoder)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
while(true) {

	// Set drive train
	int thresh = 10;
	int D = getJoystickValue(ChD);
	int C = getJoystickValue(ChC);
	int a = D + C;
	int b = D - C;
	if((a > thresh || a < -thresh) & (b > thresh || b < -thresh)) {
		setMotorSpeed(leftMotor, a);
		setMotorSpeed(rightMotor, b);
	} else {
		setMotorSpeed(leftMotor, 0);
		setMotorSpeed(rightMotor, 0);
	}

		//If Button "L-Up" or "L-Down"is pressed, we'll close the claw
		if (getJoystickValue(BtnFUp) == 1)
		{
			setMotorTarget(rampMotor, -90, 100);
			resetMotorEncoder(rampMotor);
		}
		else if (getJoystickValue(BtnFDown) == 1)
		{
			setMotorTarget(rampMotor, 90, 30);
			resetMotorEncoder(rampMotor);
		}
		else	//If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(rampMotor, 0);
		}

		//If Button "L-Up" or "L-Down"is pressed, we'll close the claw
		if (getJoystickValue(BtnLUp) == 1)
		{
			setMotorSpeed(intake, 127);
		} else if (getJoystickValue(BtnLDown) == 1) {
			setMotorSpeed(intake, -127);
		}
		else	//If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(intake, 0);
		}

		//If Button "R-Up" or "R-Down" is pressed, we'll open the claw
		if (getJoystickValue(BtnRUp) == 1) {
			setMotorSpeed(leftLiftMotor, -60);
	//		setMotorSpeed(rightLiftMotor, -50);
		} else if (getJoystickValue(BtnRDown) == 1) {
			setMotorSpeed(leftLiftMotor, 40);
	//		setMotorSpeed(rightLiftMotor, 50);
		}
		else	//If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(leftLiftMotor, 0);
		//	setMotorSpeed(rightLiftMotor, 0);
		}

	}
}
